services:
  - type: web
    name: Find_text_on_website
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python -m playwright install chromium
    startCommand: gunicorn app:app --workers 1 --threads 1 --timeout 120 --graceful-timeout 30 --worker-tmp-dir /dev/shm
